
TARGET = test

CXX_SRC = \
	test_complex.cxx \
	test_quat.cxx \
	test_moebius.cxx \
	test.cxx \

EXTRA_INC_DIRS = \
	-I.. \

include ../Makefile.defs
include ../make/Makefile.rules
include ../make/Makefile.exec
sinclude Makefile.dep

