
TARGET = esve_fltk

CXX_SRC = \
	kernel.cxx \
	ui-base.cxx \
	ui-extra.cxx \

EXTRA_INC_DIRS = \
	-I.. \
	-I../../.. \

include ../../../Makefile.defs
include ../../../make/Makefile.rules
include ../../../make/Makefile.lib
sinclude Makefile.dep

