
TARGET = poles

CXX_SRC = \
	poles.cxx \

EXTRA_INC_DIRS = \
	-I../.. \

EXTRA_OBJS = \
	../../esve/$(LIB_PREFIX)esve$(LIB_SUFFIX) \
	../../platform/fltk/esve/$(LIB_PREFIX)esve_fltk$(LIB_SUFFIX) \

include ../../Makefile.defs
include ../../make/Makefile.rules
include ../../make/Makefile.exec
sinclude Makefile.dep

